export const HttpStatusCodes = {
  // 1xx Informational
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,

  // 2xx Success
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  // 3xx Redirection
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4xx Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;

export const DefaultStatusMessages = {
  // 1xx Informational
  [HttpStatusCodes.CONTINUE]: "Continue",
  [HttpStatusCodes.SWITCHING_PROTOCOLS]: "Switching Protocols",
  [HttpStatusCodes.PROCESSING]: "Processing",
  [HttpStatusCodes.EARLY_HINTS]: "Early Hints",

  // 2xx Success
  [HttpStatusCodes.OK]: "OK",
  [HttpStatusCodes.CREATED]: "Created",
  [HttpStatusCodes.ACCEPTED]: "Accepted",
  [HttpStatusCodes.NON_AUTHORITATIVE_INFORMATION]:
    "Non-Authoritative Information",
  [HttpStatusCodes.NO_CONTENT]: "No Content",
  [HttpStatusCodes.RESET_CONTENT]: "Reset Content",
  [HttpStatusCodes.PARTIAL_CONTENT]: "Partial Content",
  [HttpStatusCodes.MULTI_STATUS]: "Multi-Status",
  [HttpStatusCodes.ALREADY_REPORTED]: "Already Reported",
  [HttpStatusCodes.IM_USED]: "IM Used",

  // 3xx Redirection
  [HttpStatusCodes.MULTIPLE_CHOICES]: "Multiple Choices",
  [HttpStatusCodes.MOVED_PERMANENTLY]: "Moved Permanently",
  [HttpStatusCodes.FOUND]: "Found",
  [HttpStatusCodes.SEE_OTHER]: "See Other",
  [HttpStatusCodes.NOT_MODIFIED]: "Not Modified",
  [HttpStatusCodes.USE_PROXY]: "Use Proxy",
  [HttpStatusCodes.TEMPORARY_REDIRECT]: "Temporary Redirect",
  [HttpStatusCodes.PERMANENT_REDIRECT]: "Permanent Redirect",

  // 4xx Client Errors
  [HttpStatusCodes.BAD_REQUEST]: "Bad Request",
  [HttpStatusCodes.UNAUTHORIZED]: "Unauthorized",
  [HttpStatusCodes.PAYMENT_REQUIRED]: "Payment Required",
  [HttpStatusCodes.FORBIDDEN]: "Forbidden",
  [HttpStatusCodes.NOT_FOUND]: "Not Found",
  [HttpStatusCodes.METHOD_NOT_ALLOWED]: "Method Not Allowed",
  [HttpStatusCodes.NOT_ACCEPTABLE]: "Not Acceptable",
  [HttpStatusCodes.PROXY_AUTHENTICATION_REQUIRED]:
    "Proxy Authentication Required",
  [HttpStatusCodes.REQUEST_TIMEOUT]: "Request Timeout",
  [HttpStatusCodes.CONFLICT]: "Conflict",
  [HttpStatusCodes.GONE]: "Gone",
  [HttpStatusCodes.LENGTH_REQUIRED]: "Length Required",
  [HttpStatusCodes.PRECONDITION_FAILED]: "Precondition Failed",
  [HttpStatusCodes.PAYLOAD_TOO_LARGE]: "Payload Too Large",
  [HttpStatusCodes.URI_TOO_LONG]: "URI Too Long",
  [HttpStatusCodes.UNSUPPORTED_MEDIA_TYPE]: "Unsupported Media Type",
  [HttpStatusCodes.RANGE_NOT_SATISFIABLE]: "Range Not Satisfiable",
  [HttpStatusCodes.EXPECTATION_FAILED]: "Expectation Failed",
  [HttpStatusCodes.IM_A_TEAPOT]: "I'm a teapot",
  [HttpStatusCodes.MISDIRECTED_REQUEST]: "Misdirected Request",
  [HttpStatusCodes.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
  [HttpStatusCodes.LOCKED]: "Locked",
  [HttpStatusCodes.FAILED_DEPENDENCY]: "Failed Dependency",
  [HttpStatusCodes.TOO_EARLY]: "Too Early",
  [HttpStatusCodes.UPGRADE_REQUIRED]: "Upgrade Required",
  [HttpStatusCodes.PRECONDITION_REQUIRED]: "Precondition Required",
  [HttpStatusCodes.TOO_MANY_REQUESTS]: "Too Many Requests",
  [HttpStatusCodes.REQUEST_HEADER_FIELDS_TOO_LARGE]:
    "Request Header Fields Too Large",
  [HttpStatusCodes.UNAVAILABLE_FOR_LEGAL_REASONS]:
    "Unavailable For Legal Reasons",

  // 5xx Server Errors
  [HttpStatusCodes.INTERNAL_SERVER_ERROR]: "Internal Server Error",
  [HttpStatusCodes.NOT_IMPLEMENTED]: "Not Implemented",
  [HttpStatusCodes.BAD_GATEWAY]: "Bad Gateway",
  [HttpStatusCodes.SERVICE_UNAVAILABLE]: "Service Unavailable",
  [HttpStatusCodes.GATEWAY_TIMEOUT]: "Gateway Timeout",
  [HttpStatusCodes.HTTP_VERSION_NOT_SUPPORTED]: "HTTP Version Not Supported",
  [HttpStatusCodes.VARIANT_ALSO_NEGOTIATES]: "Variant Also Negotiates",
  [HttpStatusCodes.INSUFFICIENT_STORAGE]: "Insufficient Storage",
  [HttpStatusCodes.LOOP_DETECTED]: "Loop Detected",
  [HttpStatusCodes.NOT_EXTENDED]: "Not Extended",
  [HttpStatusCodes.NETWORK_AUTHENTICATION_REQUIRED]:
    "Network Authentication Required",
} as const;
